[build]
  base = "/"
  publish = "dist/"

[dev]
  framework = "#static"
  port = 8888
  publish = "dist/"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

   [headers.values]
    Cache-Control = """
      max-age=0,
      no-cache,
      must-revalidate
    """
    Content-Security-Policy = "default-src 'none'; connect-src 'self'; font-src *.typekit.net; img-src 'self'; manifest-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net/npm/vue@2.6.12 https://unpkg.com/vue-router@2.0.0/dist/vue-router.min.js; style-src 'self' *.typekit.net; base-uri 'self'; form-action 'none'; upgrade-insecure-requests;"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
